src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $lang;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $article;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $sub_category;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $modify_at;

    /**
     * @ORM\OneToOne(targetEntity=ArticleCover::class, cascade={"persist", "remove"})
     */
    private $cover;

    /**
     * @ORM\Column(type="text")
     */
    private $introduction;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $categoryLogo;

    /**
     * @ORM\OneToOne(targetEntity=ArticleStat::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $article_stat;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $author_name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $author_id;

    public function __construct(){
        $this->setCreatedAt(new \DateTime());
        $this->setModifyAt(new \DateTime());
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLang(): ?string
    {
        return $this->lang;
    }

    public function setLang(string $lang): self
    {
        $this->lang = $lang;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getArticle(): ?string
    {
        return $this->article;
    }

    public function setArticle(string $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getSubCategory(): ?string
    {
        return $this->sub_category;
    }

    public function setSubCategory(string $sub_category): self
    {
        $this->sub_category = $sub_category;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifyAt(): ?\DateTimeInterface
    {
        return $this->modify_at;
    }

    public function setModifyAt(\DateTimeInterface $modify_at): self
    {
        $this->modify_at = $modify_at;

        return $this;
    }

    public function getCover(): ?ArticleCover
    {
        return $this->cover;
    }

    public function setCover(?ArticleCover $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getCategoryLogo(): ?string
    {
        return $this->categoryLogo;
    }

    public function setCategoryLogo(string $categoryLogo): self
    {
        $this->categoryLogo = $categoryLogo;

        return $this;
    }

    public function getArticleStat(): ?ArticleStat
    {
        return $this->article_stat;
    }

    public function setArticleStat(ArticleStat $article_stat): self
    {
        $this->article_stat = $article_stat;
        return $this;
    }
    /**
    * @ORM\PostLoad
    */
    public function addView(){
        $this->getArticleStat()->addView();
    }

    public function getAuthorName(): ?string
    {
        return $this->author_name;
    }

    public function setAuthorName(?string $author_name): self
    {
        $this->author_name = $author_name;

        return $this;
    }

    public function getAuthorId(): ?int
    {
        return $this->author_id;
    }

    public function setAuthorId(?int $author_id): self
    {
        $this->author_id = $author_id;

        return $this;
    }
}

templates/backend/includes/manageBundle/_add_SubCategory_form.html.twig
{{ form_start(addSubCategoryForm,{'action':path('add.sub_category')} ) }}
	{{ form_label(addSubCategoryForm.name, "Sélectionner la catégorie") }}
	{{ form_widget(addSubCategoryForm.name, {'attr': {'class': 'category'}}) }}
	{{ form_label(addSubCategoryForm.sub_category, "Nom de la sous-catégorie") }}
	{{ form_widget(addSubCategoryForm.sub_category, {'attr': {'class': 'category'}}) }}
	<button type="submit" class="bt-global" name="add-sub-category">Ajouter</button>
	{{ form_rest(addSubCategoryForm) }}
 {{ form_end(addSubCategoryForm) }}

templates/backend/includes/manageBundle/_add_category_form.html.twig
 {{ form_start(addCategoryForm,{'action': path('add_category')} ) }}
	 {{ form_label(addCategoryForm.name, "Nom de la catégorie") }}
	 {{ form_widget(addCategoryForm.name, {'attr': {'class': 'category', 'placeholder':'Entrer le nom de la catégorie'}}) }}
	 {{ form_label(addCategoryForm.logotype, "Logo type") }}
	 {{ form_widget(addCategoryForm.logotype, {'attr': {'class': 'category', 'placeholder':'Ex: fas fa-home'}}) }}
	  <button type="submit" class="bt-global" name="add-category">Créer</button>
	 {{ form_rest(addCategoryForm) }}
	 
 {{ form_end(addCategoryForm) }}

templates/backend/includes/manageBundle/_manage_categorys.html.twig
{% for message in app.flashes('success') %}
	<div class="message-banner">
		<span class="message success">
			{{message}}
		</span>
	</div>	
{% endfor %}
{% for message in app.flashes('error') %}
	<div class="message-banner">
		<span class="message error">
			{{message}}
		</span>
	</div>	
{% endfor %}
<div class="manage-ctg-w">
	<div class="manage-ctg-forms">
		<div class="ctg-add">
			<h3>Créer une nouvelle catégorie</h3>
			{{render(controller('App\\Controller\\ArticleCategoryController:addCategory'))}}
		</div>
		<div class="sub-ctg-add">
			<h3>Ajouter des sous-catégories</h3>
			{{render(controller('App\\Controller\\ArticleCategoryController:addSubCategory'))}}
		</div>
	</div>
	<div class="manage-ctg-l">
		{{render(controller('App\\Controller\\ArticleCategoryController:viewAllCategory'))}}
	</div>
</div>

templates/backend/includes/manageBundle/_manage_user_add.html.twig
{% for message in app.flashes('success') %}
	<div class="message-banner" style="width:500px">
		<span class="message success">
			Le compte de <strong style="color:#fff10c">{{message}}</strong> a été créé
		</span>
	</div>	
{% endfor %}
{{form_start(add_user_form)}}
<ul class="add-user-c">
	<li class="add-user-i">
		<ul class="add-user-group">
			<li class="add-user-group-i g1">
				{{form_label(add_user_form.familyname, "Nom")}}
				{{form_widget(add_user_form.familyname, {'attr':{
					'class':'add-user-input g1',
					'placeholder':'Entrez le nom'
				}})}}
			</li>
			<li class="add-user-group-i g1">
				{{form_label(add_user_form.firstname, "Prénom")}}
				{{form_widget(add_user_form.firstname, {'attr':{
					'class':'add-user-input g1',
					'placeholder':'Entrez le prénom'
				}})}}
			</li>
			<li class="add-user-group-i g1">
				{{form_label(add_user_form.username, "Nom d'utilisateur")}}
				{{form_widget(add_user_form.username, {'attr':{
					'class':'add-user-input g1',
					'placeholder':'Entrez le pseudo'
				}})}}
			</li>
		</ul>
	</li>
	<li class="add-user-i">
		<ul class="add-user-group">
			<li class="add-user-group-i g2">
				{{form_label(add_user_form.tel, "Téléphone")}}
				{{form_widget(add_user_form.tel, {'attr':{
					'class':'add-user-input g2',
					'placeholder':'Ex: +25775656002'
				}})}}
			</li>
			<li class="add-user-group-i g2">
				{{form_label(add_user_form.email, "Email")}}
				{{form_widget(add_user_form.email, {'attr':{
					'class':'add-user-input g2',
					'placeholder':'Entrez l\'addresse email'
				}})}}
			</li>
		</ul>
	</li>
	<li class="add-user-i">
		<ul class="add-user-group">
			<li class="add-user-group-i">
				{{form_label(add_user_form.sexe, "Sexe")}}
				{{form_widget(add_user_form.sexe, {'attr':{
					'class':'add-user-sexe',
				}})}}
			</li>
			<li class="add-user-group-i">
				{{form_label(add_user_form.nationality, "Nationalité")}}
				{{form_widget(add_user_form.nationality, {'attr':{
					'class':'add-user-nationnality',
					'placeholder':'Entrez la nationalité',
					'value':'Burundaise'
				}})}}
			</li>
			<li class="add-user-group-i">
				{{form_label(add_user_form.occupation, "Occupation")}}
				{{form_widget(add_user_form.occupation, {'attr':{
					'class':'add-user-occupation',
					'placeholder':'Ex: Etudiant ou Enseignant'
				}})}}
			</li>
			<li class="add-user-group-i">
				<label class="required" for="admin_roles">Autorité</label>
				<select name="admin[roles]" id="admin_roles" class="add-user-role">
					<option value="ROLE_BLOGGER">Bloggeur</option>
					<option value="ROLE_READER">Lecteur</option>
					<option value="ROLE_ADMIN">Administrateur</option>
				</select>
			</li>
		</ul>
	</li>
	<li class="add-user-i">
		{{form_label(add_user_form.biography, "Biographie")}}
		{{form_widget(add_user_form.biography, {'attr':{
			'class':'add-user-biography',
			'placeholder':'Ex: la passion, proverbe, etc...'
		}})}}
	</li>
	<li class="add_user_i">
		<ul class="add-user-group">
			<li class="add-user-group-i">
				{{form_label(add_user_form.job, "Rôle")}}
				{{form_widget(add_user_form.job, {'attr':{
					'class':'add-user-password',
					'placeholder':'Entrez le rôle sur le site',
					'autocomplete':'off'
				}})}}
			</li>
			<li class="add-user-group-i">
				{{form_label(add_user_form.password, "Mot de passe")}}
				{{form_widget(add_user_form.password, {'attr':{
					'class':'add-user-password',
					'placeholder':'Entrez le mot de passe',
					'autocomplete':'off'
				}})}}
			</li>
		</ul>
	</li>
</ul>
<button class="bt-global" type="submit">Enregister</button>
{{form_end(add_user_form)}}

templates/backend/includes/manageBundle/_manage_view_categorys.html.twig
<ul class="manage-ctg-l-container">
	{% for category in data %}
		<li class="manage-ctg-l-i">
			<div class="manage-ctg-category">
				<span><i class="{{category.logotype}}"></i> {{category.name}}</span>
				<span class="logo"><i class="fas fa-plus"></i></span>
			</div>
			<ul class="manage-ctg-subcategory">
				{% for sub_category in category.subCategory %}
					<li class="subcategory">
						<span>{{sub_category}}</span>
					</li>
					<span id="{{sub_category}}" class="manage-sctg-delete {{category.id}}">
						<div style="display:none">
							<span class="id">{{category.id}}</span>
							<span class="ctg">{{category.name}}</span>
							<span class="s-ctg">{{sub_category}}</span>
						</div>
						<i class="fas fa-times" id=""></i>
					</span>
					<script type="text/javascript">
						(function(){
							var filter = $('.manage-sctg-delete').filter('.{{category.id}}')
																 .filter('#{{sub_category}}'),
								id = filter.find('.id').text(),
								category = filter.find('.ctg').text(),
								subCategory = filter.find('.s-ctg').text();	

							filter.on('click', function(e){
								$('#pop-up').css({'display':'block'	});
								$('#subcategory-todelete').text(subCategory);
								$('#category-container').text(category);
								$('#del-subcategory-link').attr('href', "{{path('admin.del-subcategory')}}?subcategory="+subCategory+"&category="+category+"&in="+id);
							});

						})();
					</script>
				{% endfor %}
			</ul>
		</li>
		<span id="manage-ctg-delete"><i class="fas fa-trash-alt"></i></span>
	{% endfor %}
</ul>
<div id="pop-up" >
	<div class="message-c">
		<p>
			Vous êtes sûr de vouloir la sous-catégorie "<strong id="subcategory-todelete"></strong>" de la catégorie "<strong id="category-container"></strong>" ?
			<ul class="pop-up-choise">
				<li><a href="" class="choise yes" id="del-subcategory-link">Oui</a></li>
				<li><span class="choise no" id="choise-no">Non</span></li>
			</ul>	
		</p>
	</div>
</div>
<script type="text/javascript" src="{{asset('/js/manage_ctgs.js')}}"></script>